### ISSUE TITLE
Some typos/sentence issues in Section: Overview

### ISSUE THREAD

**Issue by okkhoy** [nus-cs2103/website#10]
1. Some ~~more~~ less important info in a panel : remove "more"
![image](https://user-images.githubusercontent.com/1023494/29021201-49fb7a58-7b97-11e7-9e20-330331ace4c2.png)

2. In the image below: "Whether a refactoring improves the code or degrades ~~it~~ depends on the situation. " : remove "it"
![image](https://user-images.githubusercontent.com/1023494/29022862-a59f725a-7b9d-11e7-86e0-881c20635250.png)

3. Can we give some real example? Like What is the difference between *scripted testing* and *exploratory testing?* instead of  what is the difference between *aaa* and *bbb*?
![image](https://user-images.githubusercontent.com/1023494/29052624-df8cfee4-7c1d-11e7-846d-f47dde2357f2.png)

4. Typo: ... **your** chances of getting ... not **you**
![image](https://user-images.githubusercontent.com/1023494/29052723-789706ac-7c1e-11e7-8de9-dfdfe2dd0640.png)

**Comment by acjh** [comment]
1. Also, "boarder-less" → "borderless"
2. Either "improves the code or degrades **it**" or "improves or degrades the code"
