### ISSUE TITLE
Remove headings.js and its reference

### ISSUE THREAD

**Issue by jkt001** [nus-cs2103/website#121]
The file headings.js is not inside the contents folder, but is located in the scripts folder (which is not inside the contents folder). 

<img width="1734" alt="screen shot 2015-12-28 at 04 56 25" src="https://cloud.githubusercontent.com/assets/8586215/12012266/8aea110c-ad1f-11e5-87cc-da4b069664cb.png">

the file headings.html is inside the contents folder, hence the current way of calling headings.js will always result in a file not found error.

**Comment by wkurniawan07** [comment]
Actually, this is a page function that is no longer needed so we can remove it and the js file involved instead.
