### ISSUE TITLE
Organise files inside contents

### ISSUE THREAD

**Issue by jkt001** [nus-cs2103/website#127]
Currently, the contents inside the contents folder is mixed, i.e. the content for handbook is mixed with schedule, coding style, etc. 

A good practice is to create subfolders for each type of content, i.e.

contents/handbook/...
contents/schedule/...
contents/coding-style/...
etc.

e.g. 
contents/schedule/week0.html
contents/handbook/handbook-lectures.html

and then update all references to the organised files.

if my suggestion is ok, I will do this as soon as possible.

**Comment by wkurniawan07** [comment]
This will be good to do, but I suggest postponing this first as currently there is at least one PR that's modifying the contents of that folder. Anyone who's interested in doing this can start to think on how to organize the contents, though.

**Comment by acjh** [comment]
I started working on this since there are no active PRs.
