### ISSUE TITLE
Handbook: wrong link for Java/C++ coding standards

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#149]
Handbook (under CE1) points to the old coding standard docs. The correct links can be found in the Schedule page, week 3.

**Comment by vhazali** [comment]
Do you want it to open in a new window/tab like in the schedule page, week 3?

**Comment by damithc** [comment]
I guess a new window? The Handbook page is very bulky and slow to load, so we don't want the user to navigate away from it by mistake and have to reload the page again.
