### ISSUE TITLE
Panel missing/messed up?

### ISSUE THREAD

**Issue by okkhoy** [nus-cs2103/website#15]
Navigate to Week 2 -> Outcomes -> Can commit using Git -> Git and Github Init 
The panel appears as dashed lines `---------`
![image](https://user-images.githubusercontent.com/1023494/29066458-d57e2d1c-7c61-11e7-9908-e1a40e264df2.png)

On a related note, the Git and Github: Init panel doesn't have the controls like other panes.
![image](https://user-images.githubusercontent.com/1023494/29066536-101f14a4-7c62-11e7-9dfc-2e46754ad721.png)

**Comment by damithc** [comment]
The blank line represents collapsed content. Click to expand.
Yes, missing controls is a known bug. Yet to be fixed.

**Comment by okkhoy** [comment]
I didn't realize the git and github was a panel :-P accidentally it opened up. Hence noticed the line.

I guess there is nothing about the dashed line in the overview section to indicate it is  collapsed content (or did I not read carefully enough!)?

**Comment by damithc** [comment]
> I guess there is nothing about the dashed line in the overview section to indicate it is collapsed content (or did I not read carefully enough!)?

It's not mentioned. Will add.

**Comment by damithc** [comment]
Added.
