### ISSUE TITLE
Improve text layout on mobile device

### ISSUE THREAD

**Issue by acjh** [nus-cs2103/website#155]
For any smartphone whose view is 500px or below.

- Currently only about 2-4 words for bullet points
<img src="https://cloud.githubusercontent.com/assets/14091939/12214834/c5afacd4-b6de-11e5-9b39-4972a82e8be6.png" width="300">

- Table text shown in excessively large font-size
<img src="https://cloud.githubusercontent.com/assets/14091939/12214943/589172d2-b6e2-11e5-871f-8553a97a0b46.png" width="300">

**Comment by damithc** [comment]
W.r.t. this, we should decide the minimum resolution we support. Those who read the module website using smart phones are unlikely to use very low-end phones.

**Comment by acjh** [comment]
Actually, 500px (as interpreted by CSS media queries) is not that low.

- Apple iPhone 6s
Actual resolution: 750 x 1334
CSS Pixel Ratio: 2
Interpreted resolution: (750/2) x (1334/2) = 375 x 667

When viewing a web page, the CSS will think the device has a 375x667 resolution screen and Media Queries will respond as if the screen is 375x667. But the rendered elements on the screen will be twice as sharp as an actual 375x667 screen.

- Samsung Galaxy S4
Actual Resolution: 1080 x 1920
CSS Pixel Ratio: 3
Interpreted Resolution: (1080/3) x (1920/3) = 360 x 640

- iPhone 5s
Actual Resolution: 640 x 1136
CSS Pixel Ratio: 2
Interpreted Resolution: (640/2) x (1136/2) = 320 x 568

Sources:
1. http://www.javascriptkit.com/dhtmltutors/cssmediaqueries2.shtml
2. http://stackoverflow.com/questions/8785643/what-exactly-is-device-pixel-ratio

**Comment by acjh** [comment]
It should be reasonable to set the minimum resolution we support as 320x480.
