### ISSUE TITLE
C++ coding standard, Dennis Ritchie name should be under the photo

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#157]
Currently, it can appear on the right of the photo.

![image](https://cloud.githubusercontent.com/assets/1673303/12219478/71a8b57a-b780-11e5-8f8a-49c0a3a051c1.png)

**Comment by acjh** [comment]
Note that this issue no longer appears after a max-width was set.
The intended fix is to add <code>\<br\></code> as done in <a href="http://acjh.github.io/website/contents/coding-standards-java.html">coding-standards-java</a>.

**Comment by acjh** [comment]
We no longer have a C++ coding standard.
