### ISSUE TITLE
C++ coding standard: style violation in sample code

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#160]
The catch should be in the same line as brace.
![image](https://cloud.githubusercontent.com/assets/1673303/12219860/b927c5d0-b78f-11e5-8694-2b86b1e7a597.png)

**Comment by damithc** [comment]
1. Needs to be fixed on both sides. 
2. Is the "blah blah blah" part relevant to this style guideline? If not, it should be removed too. The two sample should be similar except for the guideline being discussed. 
3. Is it possible to highlight the different part of the code? e.g. make it bold?

**Comment by nicholasluimy** [comment]
attempt at fixing all 3 points #166 . Pardon the misnamed branch

**Comment by damithc** [comment]
While you wait for @wkurniawan07 to review this PR, take note of the guidelines for naming PRs. The PR description (i.e. the first comment on this thread) needs to follow a certain format too.

**Comment by damithc** [comment]
No longer relevant as we don't use C++ anymore.
