### ISSUE TITLE
Some typos/sentence issues in Section: Week2 

### ISSUE THREAD

**Issue by okkhoy** [nus-cs2103/website#17]
1. Outcomes -> Can use git to save history-> Can commit using Git
**Do some changes to fruits.txt (e.g. add some text and delete some text).**
The text `fruits.txt` is typeset in monospace font elsewhere. In this line, it is normal text. May be change to code font to make it look uniform?
![image](https://user-images.githubusercontent.com/1023494/29066621-572d3772-7c62-11e7-93b9-0b3d78f70b61.png)

2. Outcomes -> Can use basic features of an IDE -> Can explain IDEs
I feel it may be not be fully appropriate to call IDEs as "sophisticated editors" :-P
In the same section, the line about debuggers can be re-worded if possible

3. Outcomes -> Can use basic features of an IDE -> Can setup a project in an IDE
Is it OK to have the video in the tab marked text description? I do understand that there is a separate video for this section in the video tab.
![image](https://user-images.githubusercontent.com/1023494/29067219-67a0df8a-7c64-11e7-8dd5-c96e705156f9.png)

4. OCD! when referring to something like a specific name of a file or path e.g., `longfile.html` or `test data`, can we use monospace fonts?
E.g: Under Outcomes -> Can automate simple regression testing of text UIs -> Can explain testing -> Example
![image](https://user-images.githubusercontent.com/1023494/29067477-505e2048-7c65-11e7-9e93-4afc963753be.png)

5. Can we provide the reference as a pop up? 
Outcomes -> Can automate simple regression testing of text UIs -> Can explain testing -> A deeper look at the definition of testing 
Source:  SWEBOKv3
Not too sure at this point what is **SWEBOKv3**
![image](https://user-images.githubusercontent.com/1023494/29067564-b7c86ffe-7c65-11e7-8cd2-10caf15f7e6e.png)

PS: Will add more when found. Haven't completed reading the section.

**Comment by damithc** [comment]
@okkhoy can create a separate issue for each bug? That way I can pick which ones to fix now and which to defer to later.

**Comment by okkhoy** [comment]
@damithc  will do

**Comment by damithc** [comment]
Item 3: The video is not part of the tab. Unfortunately, the styling of tabs doesn't show where the tab ends. :-p There is a pending issue for it.

**Comment by damithc** [comment]
Fixed.
