### ISSUE TITLE
Java coding standard: limit the page width

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#175]
Limit width to increase readability
![image](https://cloud.githubusercontent.com/assets/1673303/16988809/44fa2082-4ec4-11e6-9518-6ce4d8abfc99.png)

**Comment by acjh** [comment]
I believe this was fixed in PR #161 with issue #158 (closed).
Were you looking at the [AY1516S1](http://www.comp.nus.edu.sg/~cs2103/AY1516S1/contents/coding-standards-java.html) website? See [AY1516S2](http://www.comp.nus.edu.sg/~cs2103/AY1516S2/contents/coding-standards-java.html).

**Comment by damithc** [comment]
Yes, you are right.
