### ISSUE TITLE
Typo in the overview

### ISSUE THREAD

**Issue by Beckid** [nus-cs2103/website#18]
In "A typical CS2103/T week" section, "Admin: Lecture" sub-section:
"_Tey_ are only an aid for lecture delivery. " should be changed to "**They** are only an aid for lecture delivery. "

“Admin: Learning Outcomes” sub-section:
"They are categorized _using using_ the following star-rating system:" should be changed to "They are categorized **using** the following star-rating system:"

**Comment by damithc** [comment]
Thanks @Beckid. Will fix.
