### ISSUE TITLE
Format/font change in : Outcomes -> Can use git to save history-> Can commit using Git 

### ISSUE THREAD

**Issue by okkhoy** [nus-cs2103/website#19]
**Do some changes to fruits.txt (e.g. add some text and delete some text).**
The text `fruits.txt` is typeset in monospace font elsewhere. In this line, it is normal text. May be change to code font to make it look uniform?
![image](https://user-images.githubusercontent.com/1023494/29066621-572d3772-7c62-11e7-93b9-0b3d78f70b61.png)

Splitting #17 to multiple issues

**Comment by damithc** [comment]
Fixed.
