### ISSUE TITLE
V0.5 Documentation section links to wrong file

### ISSUE THREAD

**Issue by INCENDE** [nus-cs2103/website#190]
http://www.comp.nus.edu.sg/~cs2103/AY1617S1/contents/handbook.html#handbook-project-v05

The line "Copy paste content into a doc file. Follow this template exactly."
Links to http://www.comp.nus.edu.sg/~cs2103/AY1617S1/files/Getting%20started%20with%20Eclipse.pptx

**Comment by damithc** [comment]
Fixed. Thanks for the bug report @INCENDE
