### ISSUE TITLE
Cleanup README.md: Remove whitespace, fix punctuations and numbering

### ISSUE THREAD

**Issue by acjh** [nus-cs2103/website#204]
![Example](https://cloud.githubusercontent.com/assets/14091939/21071182/71dc7f30-bed3-11e6-8d04-8cd52792e0a1.png)

**Comment by damithc** [comment]
The numbers are auto-generated by GitHub, so it may be ok for them to be incorrect. This happens when an item is inserted into a list later and item numbers above it are left alone because we want to minimize the size of the modification.
