### ISSUE TITLE
Video in text tab: Outcomes -> Can use basic features of an IDE -> Can setup a project in an IDE

### ISSUE THREAD

**Issue by okkhoy** [nus-cs2103/website#21]
Is it OK to have the video in the tab marked text description? I do understand that there is a separate video for this section in the video tab.
![image](https://user-images.githubusercontent.com/1023494/29067219-67a0df8a-7c64-11e7-8dd5-c96e705156f9.png)

Splitting #17 to multiple issues

**Comment by damithc** [comment]
The video is not part of the tab. Unfortunately, the tab styling doesn't show where it ends.
