### ISSUE TITLE
Format/font change requested: Outcomes -> Can automate simple regression testing of text UIs -> Can explain testing -> Example

### ISSUE THREAD

**Issue by okkhoy** [nus-cs2103/website#22]
Pardon my  OCD! when referring to something like a specific name of a file or path e.g., `longfile.html` or `test data`, can we use monospace fonts?
E.g: Under Outcomes -> Can automate simple regression testing of text UIs -> Can explain testing -> Example
![image](https://user-images.githubusercontent.com/1023494/29067477-505e2048-7c65-11e7-9e93-4afc963753be.png)

Splitting #17 to multiple issues

**Comment by damithc** [comment]
Fixed
