### ISSUE TITLE
Generate anchors for markdown headers in coding standards

### ISSUE THREAD

**Issue by acjh** [nus-cs2103/website#222]
Anchors for headers (from `.md` file) do not work when rendered in HTML:
- [.../contents/coding-standards-html.html](http://www.comp.nus.edu.sg/~cs2103/AY1617S1/contents/coding-standards-html.html)
- [.../contents/coding-standards-java.html](http://www.comp.nus.edu.sg/~cs2103/AY1617S1/contents/coding-standards-java.html)
- [.../contents/coding-standards-css.html](https://rawgit.com/nsaiisasidhar/website/92-add-a-CSS-coding-standard/contents/coding-standards-css.html) (PR #197, not merged yet)

**Comment by damithc** [comment]
Actually, these pages should be deleted from this repo. Instead, we should point to the versions in https://github.com/oss-generic/process/
They have the same problem though :-)
