### ISSUE TITLE
Request: reference as a pop up

### ISSUE THREAD

**Issue by okkhoy** [nus-cs2103/website#23]
Can we provide the reference as a pop up? 
Outcomes -> Can automate simple regression testing of text UIs -> Can explain testing -> A deeper look at the definition of testing 
Source:  SWEBOKv3
Not too sure at this point what is **SWEBOKv3**
![image](https://user-images.githubusercontent.com/1023494/29067564-b7c86ffe-7c65-11e7-8cd2-10caf15f7e6e.png)

Splitting #17 to multiple issues

**Comment by damithc** [comment]
Fixed.
