### ISSUE TITLE
Empty contents under some subheadings

### ISSUE THREAD

**Issue by yj-soh** [nus-cs2103/website#24]
![2unnamed](https://cloud.githubusercontent.com/assets/8586080/10195618/20e08208-67c1-11e5-826f-2c2e270b2dfb.png)
These empty parts are confusing.
Students may wonder if it's just not loading.
Best would be to remove the arrow and click event?
Or at least some text to mention the lack of text.

**Comment by damithc** [comment]
I'll be filling out these over time.

**Comment by acjh** [comment]
Closing because the issue is no longer relevant.
