### ISSUE TITLE
Misleading visual representation of links

### ISSUE THREAD

**Issue by yj-soh** [nus-cs2103/website#25]
![3unnamed](https://cloud.githubusercontent.com/assets/8586080/10195644/3ee92e94-67c1-11e5-9f92-5989d14239cc.png)
Colours used in links aren't very good.
Blue is the recognised colour for links, but external links are just black and underlined in the content.
Internal links (the blue ones) loads content via AJAX, but it's not clear that it's a link either because hovering over it gives you a vertical bar instead of the usual hand.
Some sort of indicator for AJAX-loading-in-progress would help too; clicking on those give no immediate indication anything even happened.

**Comment by damithc** [comment]
I've changed the color of all links to the standard blue. Still, it's not a complete solution. We should also distinguish between AJAX links and normal links.
