### ISSUE TITLE
Text hard to read due to page's width

### ISSUE THREAD

**Issue by yj-soh** [nus-cs2103/website#26]
The width of the page is a real problem.
Text spreading over 100% width is extremely hard to read as your eyes have to scroll through it all the way horizontally.
A max width in some container div would definitely help.

**Comment by crispyfridge** [comment]
@damithc The body element currently has a 1000px max width from common.css. Is there something else that should be added on top of that max width?

**Comment by damithc** [comment]
Yes, I guess this issue is no longer applicable. Closing.
