### ISSUE TITLE
Support proper browsing on mobile device

### ISSUE THREAD

**Issue by yj-soh** [nus-cs2103/website#27]
There's no mobile view, is there?
For example, on Firefox on Android, it shows the whole page without any attempt to resize anything.
As a result, everything is tiny and when zoomed in, you have to manually scroll horizontally to read what is there.
The right-side buttons are pretty difficult to tap too.

**Comment by acjh** [comment]
Nice fix @vhazali
Do you mind if I take over mobile support after your PR is merged? I actually proposed to work on improving the mobile-friendliness of the website for my CS2103R project (@damithc has approved).

Please feel free to provide suggestions on possible improvements. As I only started seriously with JavaScript and CSS after Sem 1, I have much to work on and I appreciate any guidance I can get.

I'll open new Issue(s) over the weekend (after this one has been closed) for the following:
- Alternative display of images which appear too small (e.g. pop-up on tapping the image)
- Tweak the text layout (currently only about 5 words per line, or 2 words for bullet points)

Should I create a general Issue (similar to the way this one is phrased) or separate ones?

Thank you in advance. Happy New Year everyone!

Cheers,
Aaron (new guy)

**Comment by vhazali** [comment]
@acjh thanks! and sure thing! I've also just started on html and js myself. It'll be great if you could improve on the mobile optimisation. I think I've barely done anything to make the site mobile-optimised. There's really a lot of things left to be done, and it would involve a lot of changes to the current code =/
Will be glad to help out in any way I can! 

And of course, HAPPY NEW YEAR!

**Comment by damithc** [comment]
@acjh it's ok if some mobile friendliness is introduced while you are working on the CS2103R, as the sooner those things improve the better it is for users. You can still evaluate the mobile friendliness to confirm the website is indeed mobile friendly. If there aren't anything to improve in this website, your project can expand to TEAMMATES.

**Comment by acjh** [comment]
@damithc Okay noted :)

**Comment by wkurniawan07** [comment]
@acjh @vhazali I won't say that I'm *that* experienced, but if you need my advice for this website's (or TEAMMATES) development, I'll be glad to share one or two.
