### ISSUE TITLE
Suggestions: Open the link in a new page 

### ISSUE THREAD

**Issue by April0616** [nus-cs2103/website#27]
Opening the link in a new page is more convenient for students to browse the contents.
If not, after we click 'return button', the original page will be refreshed, and the old position we've visited cannot be found.
Thanks

**Comment by acjh** [comment]
Duplicate #6

**Comment by damithc** [comment]
Thanks for the suggestion @April0616 Yes it is a good suggestion 👍. As mentioned in #6, not immediately doable due to a limitation in the underlying platform.
