### ISSUE TITLE
W4.3d Link not working, fail to retrieve content

### ISSUE THREAD

**Issue by yunpengn** [nus-cs2103/website#28]
In the "Evidence" part, the admin appendix E cannot be retrieved successfully.

**Comment by damithc** [comment]
Fixed. Thank for the bug report @yunpengn 
It was due to a mismatch of case (`github.md` vs `gitHub.md`) that worked in my local Windows machine but did not work on the sever (Linux).

**Comment by yunpengn** [comment]
Ohhh, that is indeed a hard-to-find bug.
