### ISSUE TITLE
Load only relevant weeks initially

### ISSUE THREAD

**Issue by yj-soh** [nus-cs2103/website#28]
It may be best to load only the relevant weeks (current and beyond) on page load and to load the others on demand.
Students are unlikely to want to refer to something from the past.

Without any indicators as to which week is loaded, the student only sees that "the page is loading" rather than "weeks x, y, z are still loading".
As a result, it may feel even slower than the old site due to the increased number of requests.
It appears there's code for a loading indicator of some sort in the JS, but I don't see anything displayed when actually using the page.

**Comment by acjh** [comment]
The current schedule page loads reasonably fast. Do we still want this feature?
A consideration, if this is implemented, is that pressing `++++` will take longer.

**Comment by damithc** [comment]
Let's close this for now.
