### ISSUE TITLE
[W5.2d] Update screenshoot from Eclipse to Intellij IDEA

### ISSUE THREAD

**Issue by yunpengn** [nus-cs2103/website#29]
_Most modern IDEs has integrated support for testing tools. The figure below shows the JUnit output when running some JUnit tests using the Eclipse IDE._

Shouldn't we use Intellij IDEA screenshoot since we used that as the default IDE anyway?

**Comment by damithc** [comment]
Good catch @yunpengn . I didn't have time to change the screenshot. But now that I think about it, may be keeping the Eclipse screenshot is better? Students are going to see the Intellij version of it anyway (when they use Intellij), and seeing how it looks in another IDE has more value?

**Comment by yunpengn** [comment]
Yes, I agree with you on this point (since I prefer Eclipse GUI in fact haha~)
