### ISSUE TITLE
Schedule page: Expand contents upon clicking subheadings

### ISSUE THREAD

**Issue by yj-soh** [nus-cs2103/website#30]
Revealing the contents upon clicking the subheadings (Deadlines, Things to Do, etc) may work better.
In the common cases of "what is there to do", or "what will happen during the tutorial", it's likely that the student will expand everything under the subheading in the end anyway.
While the current format do give a good summary, more information may be more beneficial than less for the students here.

**Comment by damithc** [comment]
@yj-soh, the '+' button of an inner panel expands it fully. Is that the behavior you wanted?

**Comment by yj-soh** [comment]
Yes, it does.
What I meant was from a UI/UX point of view.
As it is unlikely for the contents of an inner panel to be extremely long and as it is likely for a student to want to read all of that particular inner panel, expanding every item may be more useful as the default behaviour for clicking on the inner panel's heading.

For example, when opening up "Pre-Tutorial Learning Activities", it is likely they want details of every activity instead of just a particular one.
So rather than having to spend the effort on targeting and clicking on the small '+' button, it may be better to have that as the behaviour of the entire header (with the '+' changing into a '-' as well).

The HTML content is also gotten by week, so revealing all of the content under the inner panels will not incur additional bandwidth either as the data is already with them.

**Comment by damithc** [comment]
I agree, that should be the default behavior.
