### ISSUE TITLE
W5 typos

### ISSUE THREAD

**Issue by arturs68** [nus-cs2103/website#31]
In LO W5.1d it is written: "... (or bub fix, or any other modification) ...". Bub instead of a bug.
LO W5.1d in one place, at the very top, we read "Revision Conntrol" instead of Control.
There are two spellings of Centralized used, one non-oxford British English: centralised and centralized

**Comment by damithc** [comment]
Thanks for the bug reports @arturs68 
Fixed in the latest version deployed just now.
