### ISSUE TITLE
Add a way to give definitions of terms as tool tips

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#31]
e.g. when the reader hovers over a keyword, it pops up a tool tip containing the definition of the word

**Comment by jkt001** [comment]
I'll work on this issue. 

Just to clarify, what <b>keywords</b> are you expecting to be highlighted? Is it module-related or something else? Perhaps I can do what I can and add tooltips to some keywords and we can add / remove the tooltips to other keywords later on.

**Comment by damithc** [comment]
1. There should be a way to indicate that a certain word has a viewabe definition (e.g. by showing a dashed underline)
2. When the user hovers over (or click), the tool tip appears showing the definition (or more info about the word).  The definition is pulled from another file. 

I suspect there are ready-made solutions for this problem. We just have to find a suitable one.

**Comment by acjh** [comment]
Since we're already using `jquery-ui`, we can use its [`tooltip`](https://jqueryui.com/tooltip/) feature.
