### ISSUE TITLE
Add a way to load a specific part of a page into an embedded link

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#32]
Currently, embedded links loads the entire page into the page (loading sections of the handbook in the schedule page). In some cases, we might want to load only one segment of the page.

**Comment by jkt001** [comment]
One way that comes to my mind in doing this is to split the individual handbook sections into smaller, more focused parts. Is this what you expect @damithc ?

For example: break down the CE1 part in the handbook into more detailed section such as in the faq section.

**Comment by damithc** [comment]
No, that's the opposite of what I want. Instead of splitting the page into more parts, I want to be able to embed only a part of it (e.g. a specific `div`) in another page. To give an example, I would like to keep all FAQ questions in the same html file (currently each question is in a separate file) but embed specific questions in other pages.

**Comment by jkt001** [comment]
I see. I will look into it and see what I can do.

**Comment by jkt001** [comment]
I have found a way to do it and currently working on it.
