### ISSUE TITLE
Week 5 lectures: format different from other weeks

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#34]
The layout/formatting is different from other weeks and the pictures are missing.
This is week 5:
![image](https://cloud.githubusercontent.com/assets/1673303/10275234/762834d0-6b78-11e5-816e-d544eaa4b31f.png)
This is from week 4:
![image](https://cloud.githubusercontent.com/assets/1673303/10275248/8f7d4bfa-6b78-11e5-909f-a08d1d463a71.png)

**Comment by damithc** [comment]
@quarbby can you submit a new PR for this?
The workflow is given in the README.md

**Comment by quarbby** [comment]
Sorry about that. Will do it asap :)

**Comment by damithc** [comment]
Fixed.
