### ISSUE TITLE
Code-blocks in w8.5 not displaying properly

### ISSUE THREAD

**Issue by zameschua** [nus-cs2103/website#38]
### Description
The HTML elements are showing up instead of being properly formatted, where code-blocks are used.
Tested on Google Chrome, normal and incognito mode

### Examples

![image](https://user-images.githubusercontent.com/18271085/31305537-ab2112a0-ab6e-11e7-924e-9874471d3969.png)

![image](https://user-images.githubusercontent.com/18271085/31305544-def4f98e-ab6e-11e7-8d41-60b21475b810.png)

**Comment by damithc** [comment]
Seems to be a bug in the platform. Working on a workaround.

**Comment by damithc** [comment]
Thanks for the bug report @zameschua 
Applied a workaround for the problematic code examples. Please let us know if you spot any more cases.
