### ISSUE TITLE
W8.3c Raw html code appears in the page

### ISSUE THREAD

**Issue by yunpengn** [nus-cs2103/website#39]
Open the code example in W8.3c, raw HTML code comes out:
```
<span class="hljs-function"><span class="hljs-keyword">void</span> <span class="hljs-title">write</span><span class="hljs-params">()</span></span>{
    ...
}
```

**Comment by damithc** [comment]
Thanks for the bug report @yunpengn . Where exactly in W8.3c? Can give a screenshot?

**Comment by yunpengn** [comment]
See the screenshot below. Suspect it is the write method.
![W8.3c](https://user-images.githubusercontent.com/18503402/31322588-33a486f2-accd-11e7-9092-510e0010a8c5.png)

**Comment by damithc** [comment]
Ah, I overlooked that one :-p Fixed. Thanks again @yunpengn
