### ISSUE TITLE
(Leaderboard) Need to keep scrolling to see Table Header row

### ISSUE THREAD

**Issue by YijinL** [nus-cs2103/website#40]
Generally we only care about our marks, and we can see all our marks in our own rows.
However, there are so many columns for each marking submission, and with the headers all the way at the top of the table, it is hard to get the information and context we need to make sense of our marks.

One way to fix it is to fix the header row to the window.

**Comment by damithc** [comment]
It won't be easy to do because that page is served using GoogleDocs at the moment. :-p

**Comment by jkt001** [comment]
I think one way of solving this issue is to freeze the panes in Google Docs directly. It is easily done if one has access to the google sheets file. 

<img width="440" alt="screen shot 2015-12-30 at 12 52 19" src="https://cloud.githubusercontent.com/assets/8586215/12046881/3f5e3156-aef4-11e5-8eb7-f5ee3d5a019c.png">

**Comment by vhazali** [comment]
I think just freezing the panes doesn't work if the document is to be embedded into the page. 
It works if we view the shared document, but not in the current view.

**Comment by jkt001** [comment]
I see. I have never tried embedding google docs to a page before. 

We need to figure out something else then.

**Comment by vhazali** [comment]
The embedded one looks like:
![embedded gsheets](https://cloud.githubusercontent.com/assets/8543547/12048515/a0e4f954-af0e-11e5-87ad-1814312175bc.png)

The shared one looks like:
![shared ghseets](https://cloud.githubusercontent.com/assets/8543547/12048528/d31f52b6-af0e-11e5-9ce5-63c6ed1ad98a.png)

So if the title and the buttons at the top of the table is acceptable, then freezing the panes in the original gdocs would work.

**Comment by damithc** [comment]
What we need is the header row to appear at the top of the page all the time. Freezing the top row doesn't do that right?
May be use Jquery to pull the page content and convert it to a 'top row frozen' format dynamically?

**Comment by jkt001** [comment]
I am currently looking into possible approaches to solve this issue. I am away from my laptop right now and will try to work on this later. I'll let you all know if I run into problems or if I have fixed it, including my approach. 

@damithc thanks for the suggestion. I'll look into it.

**Comment by swxsw** [comment]
This may sound very hacky, but maybe an idea from me is to load 2 copies of the same document. Then overlay one over another; the one on-top should only reveal the headers and have the scroll bar removed, whereas the layer below has all the standard scrolling and display, not sure if that is a good approach :p

**Comment by acjh** [comment]
@swxsw Yes, that's what I did in #185 :)

**Comment by swxsw** [comment]
@acjh Oh nice, looks like I am on the right track to learning web dev :)

**Comment by damithc** [comment]
We have stopped using a leaderboard in the recent semesters, so let's close this for the time being.
