### ISSUE TITLE
Collapse button for every section

### ISSUE THREAD

**Issue by ChenXiaoman** [nus-cs2103/website#42]
Can we have a collapse button for in every section we open so that it saves us the time to scroll back to the title to collapse the current section? Besides, the collapse button helps us distinguish between sections. It makes it clear which section I have finish reading and should be collapsed. 
Actually, I notice that some sections have the collapse button but some don’t have (as shown in the pictures below). Can we have a collapse button for all the sections? 
Thank you!
![image](https://user-images.githubusercontent.com/25006870/31580875-89029726-b121-11e7-8ca7-50f7eb65a5a3.png)
![image](https://user-images.githubusercontent.com/25006870/31580876-937f6e9a-b121-11e7-8d6e-7302e4142167.png)

**Comment by damithc** [comment]
Good suggestion @ChenXiaoman 
Done.
