### ISSUE TITLE
Animation may not be necessary

### ISSUE THREAD

**Issue by bsmmoon** [nus-cs2103/website#45]
That 0.1 second of waiting time is somewhat frustrating, especially because there are multiple levels to open. Wouldn't faster or instant open be better?

**Comment by damithc** [comment]
We can try without it and see if the transition is too jarring without it.

**Comment by damithc** [comment]
While it is not too jarring without the animation, for now I'd rather keep the animation because it doesn't take long and is meaningful. But we'll revisit this issue again at a future time.
