### ISSUE TITLE
Typo in W10.6

### ISSUE THREAD

**Issue by ChenXiaoman** [nus-cs2103/website#46]
![image](https://user-images.githubusercontent.com/25006870/31980499-7b4d9d8a-b912-11e7-8c71-1c54bf3d3cb7.png)
[MIN_INT ... 0] : below the range that produces: false?
[13 … MAX_INT] : above the range that produces false?

**Comment by damithc** [comment]
Thanks for the bug report @ChenXiaoman 
It's actually correct but probably should bold the words **below** and **above**.

**Comment by damithc** [comment]
Fixed.
