### ISSUE TITLE
Minesweeper AD is not precise

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#47]
![image](https://user-images.githubusercontent.com/1673303/32991038-425a1a00-cd6f-11e7-98c0-5a22ba2d7efe.png)

https://nus-cs2103.github.io/website/book/uml/activityDiagrams/basicNotations/combined/

**Comment by chrisboo** [comment]
![ad](https://user-images.githubusercontent.com/7839537/32991202-ead437c2-cd71-11e7-9fed-1cc9432abb5b.jpg)

I have found a way to fix the problem. Does this image fully captures the interaction? I have leave out the rests that aren't affected.

**Comment by damithc** [comment]
The entire question has been removed. Modeling a, b, and c precisely and in the same diagram results in a diagram that is too complicated or practical use.
