### ISSUE TITLE
Convert 'points to ponder' doc to html

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#51]
The current page is here https://docs.google.com/document/d/1_4r9JmKvXkcqfATgNe3xPvRHnM32QuJOu4DfegUpd7I/pub?embedded%3Dtrue

This doc is linked from T9 description.

**Comment by crispyfridge** [comment]
For the html files created from the google docs, should the scripts and content from google be removed?

**Comment by damithc** [comment]
Copy just the content, not the html/css/js, from the google doc.
