### ISSUE TITLE
Leaderboard too many column makes it harder to point our score.

### ISSUE THREAD

**Issue by 9gix** [nus-cs2103/website#53]
If we scroll right, we lose track which of the row is for our particular score. Also what score is that. 

One possible solution I guess it to use a fixed position of the column for "group-id" and "name" upon scrolling right.

Additionally, we may also need to keep the column description fixed at the top position when scroll down.

**Comment by 9gix** [comment]
Just saw another very similar issues #26

**Comment by damithc** [comment]
Same as #40 ?

**Comment by 9gix** [comment]
Yes, duplicate of #40
