### ISSUE TITLE
Typo in week 11 verstion --> version

### ISSUE THREAD

**Issue by zjdljb** [nus-cs2103/website#54]
Week 11 tutorial 10 Demo V0.3

Verstion should be version
<img width="1280" alt="screen shot 2015-10-29 at 10 52 06 am" src="https://cloud.githubusercontent.com/assets/4532688/10808867/3147d5a8-7e2b-11e5-9833-1f0cb82976a4.png">

**Comment by damithc** [comment]
Good job spotting the typo @zjdljb 
I'll leave it as an opportunity for someone to contribute by fixing it.
