### ISSUE TITLE
Missing Word in Handbook Section on Work Distribution

### ISSUE THREAD

**Issue by Foleosy** [nus-cs2103/website#55]
There is a missing word in the subsection of "Policy on project work distribution" in Appendix B:

"It is OK to do less or more than equal share in your ____. However, be prepared to receive a different grade than [your] team members if you didn't do an equal share."

**Comment by damithc** [comment]
Thanks for spotting it and for the fix @Foleosy 
Can you edit the issue title to be more specific (in which file, which section?)

**Comment by Foleosy** [comment]
I apologise for that. It is located in the file "handbook-policy-workDistribution.html", which is under Appendix B in the handout, titled under the section "Policy on project work distribution".

**Comment by damithc** [comment]
Edit the title of this issue to be more specific. :-)
