### ISSUE TITLE
Unable to open Facebook & Google+ links in Teaching team page for Prof Damith

### ISSUE THREAD

**Issue by Foleosy** [nus-cs2103/website#58]
Tested in Google Chrome and Internet Explorer.

Left clicking the links for Facebook/Google+ in the page "Teaching team" for Prof Damith in Google Chrome (version 46.0.2490.80 m) displays "Redirecting you to https://www.facebook.com/damith.rajapakse / Redirecting you to https://plus.google.com/114919422028123491955/posts/p/pub" but they will never load.

Left clicking in Internet Explorer 11 gives the error
"This content cannot be displayed in a frame
To help protect the security of information you enter into this website, the publisher of this content does not allow it to be displayed in a frame."

Opening in a new tab/window (by means of right clicking/scroll wheel) opens the Facebook page fine, but Google+ displays a blank page with just Google+ headers.

**Comment by damithc** [comment]
Thanks for the bug report @Foleosy 
That page is currently a Google Doc, so there's not much we can do at the moment. I've added a 'open in new tab' comment as a temporary fix.

**Comment by Foleosy** [comment]
The 'open in new tab' function doesn't work for the Google+ link still. I believe it's due to the fact that it opens based on the link "https://plus.google.com/114919422028123491955/posts/p/pub", when it should be "https://plus.google.com/114919422028123491955/posts" instead.

I tested it out on my own profile, and it seems that the /p/pub at the end only works if you are signed in and looking at your own profile. If not, it'll display just a page with the header information.

**Comment by damithc** [comment]
I didn't realize it because I was logged in. Fixed. Thanks again @Foleosy
