### ISSUE TITLE
Incorrect link at Schedule > Week 4 > Lecture > Part 2 > Resources

### ISSUE THREAD

**Issue by ChiangFongSin** [nus-cs2103/website#60]
Schedule > Week 4 > Lecture > Part 2 > Resources
First bullet point > second sub-point > "this tutorial"

The link goes to part I of the tutorial:
http://www.comp.nus.edu.sg/~cs2103/AY1516S1/files/An%20introduction%20to%20Visual%20Studio%202012%20-%20part%20I.pdf

but it should actually go to part II of the tutorial:
http://www.comp.nus.edu.sg/~cs2103/AY1516S1/files/An%20introduction%20to%20Visual%20Studio%202012%20-%20part%20II.pdf

Note the missing 'I' at the end before the .pdf

**Comment by damithc** [comment]
Thanks for the bug report @ChiangFongSin 
Let's see if someone can submit a quick fix for this.

**Comment by ChiangFongSin** [comment]
Don't mention it
