### ISSUE TITLE
Missing content for/in panel: "FAQ: What if I don't carry around a laptop?"

### ISSUE THREAD

**Issue by okkhoy** [nus-cs2103/website#8]
The content reads "null"
![image](https://user-images.githubusercontent.com/1023494/29052894-703477b4-7c1f-11e7-910b-4f0abbe4021c.png)

**Comment by acjh** [comment]
[`#handbook-faq-noLaptop`](https://github.com/nus-cs2103/website/blame/1e054f4ef0289d95bead45083b8e28dccac54744/admin/tutorials.md#L54) → `#admin-faq-noLaptop`
