### ISSUE TITLE
Dead links in Section: Overview

### ISSUE THREAD

**Issue by okkhoy** [nus-cs2103/website#9]
This issue consolidates a list of dead links in the Overview section.

1. Link to the printer friendly version is dead. (https://nus-cs2103.github.io/common/print.html)
![image](https://user-images.githubusercontent.com/1023494/29022963-10400430-7b9e-11e7-9880-e14e2d31cfb1.png)

2. ~~Links to "Textbook" and "Schedule Page"~~
![image](https://user-images.githubusercontent.com/1023494/29023482-700218e8-7ba0-11e7-9045-d300eab69618.png)

3. This link: http://catb.org/~esr/faqs/smart-questions.html is flagged as "hacking" by NUS IT :-P
Need to find alternate link here
![image](https://user-images.githubusercontent.com/1023494/29052756-b2c1f88c-7c1e-11e7-811d-cf1761e88774.png)

4. The link to " A practitioner article about receiving feedback " leads back to the website.
![image](https://user-images.githubusercontent.com/1023494/29052809-f8ed0860-7c1e-11e7-8142-9dd6f252f40d.png)

5. Same as above for : "What if I don't carry a laptop around?"
![image](https://user-images.githubusercontent.com/1023494/29052855-3808c3e0-7c1f-11e7-8427-3243ce35b37d.png)

**Comment by acjh** [comment]
1. [`../common/print.html`](https://github.com/se-edu/se-book/blame/ecaadd4913a758a3c57447da0d23489ad8a3779a/about/usage.md#L142) → `{{baseUrl}}/common/print.html`
2. Works for me 🤔

**Comment by damithc** [comment]
> ../common/print.html → {{baseUrl}}/common/print.html

I tried this and doesn't seem to work. odd. 🤔

**Comment by damithc** [comment]
> ../common/print.html → {{baseUrl}}/common/print.html

After doing the above,

`<include src="../../book/about/usage.md"/>` : link works
`<include src="../../book/about/usage.md#printing"/>` : produces a broken link
`<include src="../../book/about/usage.md#printing" dynamic/>` : link works

Looks like re-basing links doesn't work for static includes that targets a div (rather than entire page)

**Comment by damithc** [comment]
@okkhoy can you check item 2? Seems to be working already.

**Comment by okkhoy** [comment]
@damithc item 2 works. i am made the edit in the initial description
